FROM rust:1.94.1-slim-bookworm
RUN apt-get update \
    && apt-get install -y git libssl-dev pkg-config ssh \
    && apt-get clean \
    && rustup component add clippy \
    && cargo install cargo-audit
