use std::net::ToSocketAddrs;

use actix_files::NamedFile;
use actix_session::storage::RedisSessionStore;

use actix_session::SessionMiddleware;
use actix_web::cookie::Key;
use actix_web::{web, App, HttpServer};
use anyhow::Context;
use base64::prelude::BASE64_STANDARD;
use base64::Engine;
use clap::Parser;
use rand::RngExt;
use redis::Client;
use sqlx::postgres::PgPoolOptions;
use sqlx::PgPool;
use tracing::warn;
use tracing_actix_web::TracingLogger;
use tracing_subscriber::EnvFilter;
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

use crate::data::User;

mod api;
mod data;
mod error;
mod keylocker;
mod logtail;
mod tls;

#[derive(OpenApi)]
#[openapi(
    paths(
        api::create_user,
        api::login,
        api::logout,
        api::verify,
        api::get_user,
        logtail::ws_logs,
        api::get_files,
        api::keylocker_api
    ),
    components(schemas(
        data::User,
        api::CreateUser,
        api::LoginRequest,
        api::SessionUser,
        api::CreateKeylockerEntry,
        api::ReadKeylockerEntries,
        api::KeylockerRequest
    ))
)]
struct ApiDoc;

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    #[arg(short = 'H', long, default_value = "localhost")]
    host: String,

    #[arg(short, long, default_value_t = 8080u16)]
    port: u16,

    /// Launch with certificates in certs directory and serve over HTTPS/TLS
    #[arg(long, default_value_t = false)]
    tls: bool,

    /// Don't include Secure flag in Cookies (enables Cookie sessions while over plain HTTP)
    #[arg(long, default_value_t = false)]
    insecure_cookies: bool,

    /// Admin account login. Try to avoid "admin" or "super" they're fairly predictable.
    #[arg(long, default_value = "elliot")]
    admin_name: String,
}

impl Args {
    fn to_sock_addr(&self) -> impl ToSocketAddrs {
        (self.host.clone(), self.port)
    }
}

/// Serve the TLS server certificate as a downloadable `server.pem` attachment.
///
/// Exposed at `/cert` when the server runs with `--tls`, so clients can trust
/// the self-signed certificate generated by [`tls::load_or_generate_config`].
async fn download_cert() -> actix_web::Result<NamedFile> {
    Ok(NamedFile::open(tls::CERT_PATH)?.set_content_disposition(
        actix_web::http::header::ContentDisposition::attachment("server.pem"),
    ))
}

/// Redact credentials from a database URL so it can be written to logs.
///
/// If the URL contains a username or password, both are replaced with `***`.
/// If the URL cannot be parsed at all, the whole string is replaced with `***`
/// rather than risk leaking a malformed secret.
fn sanitize_database_url(database_url: &str) -> String {
    match url::Url::parse(database_url) {
        Ok(mut parsed) => {
            if parsed.username() != "" {
                let _ = parsed.set_username("***");
            }
            if parsed.password().is_some() {
                let _ = parsed.set_password(Some("***"));
            }
            parsed.to_string()
        }
        Err(_) => "***".to_string(),
    }
}

/// Create or reset the admin user on startup.
///
/// The password comes from the `ADMIN_PASSWORD` env var if set; otherwise a
/// random 15-character alphanumeric password is generated and logged so the
/// operator can retrieve it from the startup output. The admin row is upserted
/// by login, so on every boot the admin password is rotated to the current
/// value — this lets operators recover access by restarting with a fresh
/// `ADMIN_PASSWORD`.
async fn initialize_admin(args: &Args, pool: &PgPool) -> anyhow::Result<()> {
    let mut rng = rand::rng();
    let password: String = if let Ok(pass) = std::env::var("ADMIN_PASSWORD") {
        pass
    } else {
        (1..16)
            .map(|_| rng.sample(rand::distr::Alphanumeric) as char)
            .collect()
    };
    tracing::info!("New session password is {}", password);
    let user = User::new(&args.admin_name, &password, None, vec!["admin".to_string()])
        .map_err(|e| anyhow::anyhow!("{e}"))
        .context("Failed to create admin user")?;
    sqlx::query("INSERT INTO users(id, login, password_hash, reset_email) VALUES ($1, $2, $3, $4) ON CONFLICT(login) DO UPDATE SET password_hash = $3")
        .bind(user.id)
        .bind(&user.login)
        .bind(&user.password_hash)
        .bind(&user.reset_email)
        .execute(pool)
        .await
        .context("Failed to upsert admin user")?;

    Ok(())
}

/// Load the cookie-signing session key from the `SESSION_SECRET` env var.
///
/// The value must be base64-encoded and decode to at least 64 bytes, which is
/// the minimum key length required by `actix_session` for signed cookies.
/// Callers are expected to fall back to a freshly generated key if this
/// returns an error, which invalidates any previously issued sessions.
fn get_session_key_from_env() -> anyhow::Result<Key> {
    let session_secret = std::env::var("SESSION_SECRET")?;
    let session_secret = BASE64_STANDARD
        .decode(session_secret)
        .context("Failed to decode SESSION_SECRET as base64")?;
    if session_secret.len() < 64 {
        return Err(anyhow::anyhow!(
            "KeyLength: SESSION_SECRET must be at least 64 bytes"
        ));
    }
    Ok(Key::from(&session_secret))
}

/// Application entry point.
///
/// Responsible for wiring together tracing, CLI args, Redis (both the session
/// store and the file-id lookup store), the Postgres pool, database migrations,
/// admin user initialization, the actix-web `App` factory, and finally binding
/// the HTTP or TLS listener before running the server.
#[actix_web::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env())
        .init();

    let args = Args::parse();

    let use_tls = args.tls;
    // Prefer a stable secret from the environment so sessions survive restarts;
    // fall back to an ephemeral random key with a loud warning.
    let secret_key = match get_session_key_from_env() {
        Ok(key) => key,
        Err(e) => {
            warn!("No session key available from environment: {}", e);
            warn!("Generating new random session key");
            Key::generate()
        }
    };

    let redis_url =
        std::env::var("REDIS_URL").unwrap_or_else(|_| "redis://127.0.0.1:6379".to_string());

    // File-id -> path lookups live in Redis DB 4 by default to keep them
    // isolated from the session store on DB 0.
    let file_redis_store = match std::env::var("FILE_REDIS_STORE") {
        Ok(url) => url,
        Err(_) => format!("{}/4", redis_url.trim_end_matches("/")),
    };
    let redis_store = RedisSessionStore::new(&redis_url)
        .await
        .context("Failed to connect to Redis")?;

    let redis_client = Client::open(file_redis_store).context("Failed to connect to redis")?;

    let database_url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://tfbs:tfbs@localhost:5432/tfbs".to_string());

    tracing::info!(
        "Creating database pool for {}",
        sanitize_database_url(&database_url)
    );
    let pool = PgPoolOptions::new()
        .max_connections(5)
        .connect(&database_url)
        .await
        .context("Failed to connect to database")?;
    tracing::info!("Migrating database");
    sqlx::migrate!()
        .run(&pool)
        .await
        .context("Failed to run migrations")?;
    tracing::info!("Migration complete");
    initialize_admin(&args, &pool).await?;
    let insecure_cookies = args.insecure_cookies;
    let server = HttpServer::new(move || {
        let mut app = App::new().wrap(TracingLogger::default());
        let mut session_mgr = SessionMiddleware::builder(redis_store.clone(), secret_key.clone());
        if insecure_cookies {
            session_mgr = session_mgr.cookie_secure(false);
        }
        if use_tls {
            app = app.route("/cert", web::get().to(download_cert));
        }
        app.wrap(session_mgr.build())
            .service(
                web::scope("/api")
                    .route("/user", web::get().to(api::get_user))
                    .route("/users", web::post().to(api::create_user))
                    .route("/login", web::post().to(api::login))
                    .route("/logout", web::get().to(api::logout))
                    .route("/verify", web::post().to(api::verify))
                    .route("/files", web::get().to(api::get_files))
                    .route("/logs/ws/{file_id}", web::get().to(logtail::ws_logs))
                    .route("/keylocker", web::post().to(api::keylocker_api)),
            )
            .service(
                SwaggerUi::new("/swagger-ui/{_:.*}")
                    .url("/api-docs/openapi.json", ApiDoc::openapi()),
            )
            .service(
                actix_files::Files::new("/", "./static")
                    .index_file("index.html")
                    .default_handler(
                        actix_files::NamedFile::open("./static/index.html")
                            .expect("Failed to open index.html"),
                    ),
            )
            .app_data(web::Data::new(pool.clone()))
            .app_data(web::Data::new(redis_client.clone()))
    });

    let server = if args.tls {
        let tls_config = tls::load_or_generate_config(&args.host)?;
        server
            .bind_rustls_0_23(args.to_sock_addr(), tls_config)
            .context(format!("Failed to bind TLS to {}:{}", args.host, args.port))?
    } else {
        server
            .bind(args.to_sock_addr())
            .context(format!("Failed to bind to {}:{}", args.host, args.port))?
    };

    server.run().await.context("Server error")?;
    Ok(())
}
